### PR TITLE
ZigBee component documentation

### PR DESCRIPTION
**Pull request by flyte**
This PR provides the documentation for the ZigBee integration and components.

I haven't been able to test this on HA itself because I wasn't able to get rake to install all of its components properly. It looks fine on Github though.

### CODE REVIEW

**Comment by balloob** [comment]
This PR has to be pointed at the `next` branch as it is for the next release.

**Comment by balloob** [comment]
Make sure you use the right Ruby version when trying to install gems. I use `rbenv` to use a different ruby version inside the HA.io repo.

**Comment by flyte** [comment]
Which version of Ruby is the right version?

**Comment by balloob** [comment]
cat .ruby-version

On Thu, Jan 28, 2016 at 9:10 AM, Ellis Percival <notifications@github.com>
wrote:

> Which version of Ruby is the right version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balloob/home-assistant.io/pull/169#issuecomment-176286992>
> .
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.

**Comment by MartinHjelmare** [comment]
RVM and Ruby 2.2.3 failed to install some of the gems. Then I tried Ruby 2.2.1, which I already had setup for Octopress, and that worked.

**Pull request closed without merging**
