### PR TITLE
Update zwave.markdown

### PR DESCRIPTION
**Pull request by devanl**
Adjust formatting on optional package creation

### CODE REVIEW

**Comment by fabaff** [comment]
Did you test that locally? I think that this will not work because it's inside a `note` block.

**Comment by devanl** [comment]
@fabaff Your comment on the markdown inside of a note is spot on but, the original was too confusing.  Maybe this isn't the best way, any ideas?

**Comment by fabaff** [comment]
I think that the fastest way for now would be to just remove `bash`. ``` is rendered into <code> which is working in `note`.

**Comment by balloob** [comment]
@fabaff that brings us back to the original state. So I'm closing this PR.

**Pull request closed without merging**
