### PR TITLE
Additional scattered info for IFTTT Documentation

### PR DESCRIPTION
**Pull request by CCOSTAN**
I entered in some additional information on setting up the Maker channel with HA.  It still needs information on setting up actual automations etc...

Once I figure that out, I will screenshot and document. :)

### CODE REVIEW

**Comment by fabaff** [comment]
Cool, thanks for your help.

**Comment by balloob** [comment]
Let's make sure we host the images on our website and not on imgur.

**Comment by CCOSTAN** [comment]
We need a python script to run through the files, download the imgur images and relink to local resources. ☺

Something that uses this: http://pyimgur.readthedocs.org/en/latest/reference.html#pyimgur.__init__.Image.download

I’m honestly not even sure how to include additional files(images) in a PR. ☹

Check out my virtualization blog at www.vCloudInfo.com<http://www.vcloudinfo.com/>!
Follow me : Twitter: @ccostan<http://www.twitter.com/ccostan> | FaceBook <http://www.facebook.com/VMwareInfo>

**Comment by balloob** [comment]
It's as easy as putting the images in the source/images/<appropriate
subfolder>/ directory. Fork, clone, add, commit, push, PR.

**Comment by balloob** [comment]
I'll merge it now and will fix this locally. I will not accept any major pull requests like this in the future as they have clearly not been tested locally.
 
Example of broken markup in the IFTTT page:
screen shot 2015-09-08 at 22 19 15

**Comment by CCOSTAN** [comment]
Sorry @balloob, thought I caught all the typos and syntax issue.  Thanks for fixing it locally.

**Comment by balloob** [comment]
Sorry if I sounded a bit harsh, I was tired but trying to get through my backlog from last weekend!

The GitHub markdown preview is not the same as that is being used by our website. GitHub seems to be a bit more flexible.

**Comment by CCOSTAN** [comment]
No sweat - I deal with Programmers in my real life. :) I know how cranky you guys can get. Haha.  On the positive side, if you are tired on mondays (or in this case tuesday), I can infer that you had a GOOD weekend! Ha!

And you are spot on with the GitHub markdown preview.  I did all my edits via the Github web interface so I put a little too much faith into what I thought would happen when it got migrated over to the real thing.  That's the single advantage to the imgur links I was using - They render properly in the markdown preview tab since they are external. 

BTW: I did look up the lifespan of the imgur images and they are permanent unless explicitly deleted.  I totally understand the desire to have them locally though but wanted to let you know.

**Pull request merged**
