### PR TITLE
New layout of components index

### PR DESCRIPTION
**Pull request by fabaff**
This is the new PR and successor of #31 for the layout changes of the components index page. The indent level of the entries was not changed to keep the option of creating a big table of all entries.

### CODE REVIEW

**Comment by balloob** [comment]
The screenshot looks good. Since your'e using the grid system the layout will also work on small devices.

I say: let's merge! :+1:

**Comment by balloob** [comment]
Because I didn't want to create merge conflicts for your PR, the following links still need to be added to component page:
 - switch.mqtt
 - sensor.mqtt
 - device_tracker.aruba

**Comment by fabaff** [comment]
Thanks. I will take care about the links.

**Comment by balloob** [comment]
I added Aruba, didn't add MQTT because not sure if it fitted really, they are already linked underneath MQTT.

**Pull request merged**
