### PR TITLE
Components overview

### PR DESCRIPTION
**Pull request by fabaff**
In #43 we were talking about a new way to handle the components overview. This is a prototype of how it could be done. 

components

All elements are stored in an array which would make it easy to add a new one. A little Javascript and a little CSS, done :-) Well not really....
It would be nice to get some feedback before we go on. The last major rework of the components page was not very sustainable. 

It would also be nice to get some support from experienced web designers because my JS/jquery/CSS knowledge is limited and Octopress is "unknown territory" for me. Thanks.

### CODE REVIEW

**Comment by fabaff** [comment]
Forgot to mention: This needs [Isotope](http://isotope.metafizzy.co/) to work.
components1

**Comment by balloob** [comment]
This is awesome! 

I can fix some of the styling when I'm home again.

**Comment by CCOSTAN** [comment]
Wow!  That's really great looking! :+1:

**Comment by fabaff** [comment]
You are kidding right? It looks like sh....The images are horizontally not in the middle, the text link is placed somewhere depending on the image size, and there a for sure 10 other issue with the design/CSS.

I just tried to get the stone rolling...but I hope that we can create a solution that looks professional and is easy to maintain.

**Comment by maddox** [comment]
maybe he can just see your vision :)

**Comment by balloob** [comment]
So I took this PR, cleaned it up a bit and merged it into master. It still needs some more clean up but it's getting really pretty. Great work @fabaff !

screen shot 2015-10-24 at 21 56 31

**Pull request merged**
